---
title: "Hausaufgabe_Session5"
output: html_document
---
Laden der Libraries und Daten 
```{r}
library(tidyverse)
library(cluster)
library(caret)
```

```{r}
all <- read_csv("all.csv")
```

Erstellung eines Dataframes 
```{r}
users_books <- all %>%
  group_by(`Book-Title`) %>%
  mutate(no_of_books = n()) %>%
  filter(no_of_books > 300) %>%
  filter(`Book-Rating` > 9) %>%
  select(`User-ID`, `Book-Title`)
  
```

```{r}
df <- data.frame(id = c(1,1,2,3,4), fruit = c("apple","pear","apple","orange","apple"))
df
df %>% mutate(i = 1) %>% spread(fruit, i, fill = 0)
```

```{r}
users_books <- users_books %>%
  unique()
books_wide <- users_books %>%
  mutate(i = 1) %>%
  spread(`Book-Title`,i,fill=0)
```

Erstellen eines Hierarchischen Clusters: 

```{r}
books.scaled <- as.data.frame(scale(books_wide))
```

```{r}
wss <- (nrow(books.scaled)-1)*sum(apply(books.scaled,2,var))
  for (i in 2:10) wss[i] <- sum(kmeans(books.scaled,
                                       centers=i)$withinss)
plot(1:10, wss, type="b", xlab="Number of Clusters",
     ylab="Within groups sum of squares")
```

```{r}
books.dist <- dist(books.scaled, method="euclidean")
books.hc <- hclust(books.dist, method = "ward.D2")
plot(books.hc)
groups <- cutree(books.hc, k=3) 
rect.hclust(books.hc, k=3, border="red")
```

```{r}
books_wide%>%
  mutate(cluster = groups) %>%
  left_join(books_wide) %>%
  select(cluster,`User-ID`)
```

Erstellen eines K Means Clusterings: 

```{r}
k.means.fit <- kmeans(books_wide, 2) 
```

```{r}
k.means.fit$size
```

```{r}
clusplot(books_wide, k.means.fit$cluster, color=TRUE, shade=TRUE,
labels=4, lines=0, main="K-means cluster plot")
```

```{r}
table(books_wide$`User-ID`,k.means.fit$cluster)
```

Welche Bücher sind in welchem Cluster?

Anscheinend gehören alle Bücher dem 2. Cluster an. 
